### ISSUE TITLE
Redundant data augmentation during training

### ISSUE THREAD

**Issue by legnaib** [PeterL1n/BackgroundMattingV2#149]
I'm not sure if I have understood this correctly: In the training phase (in both scripts train_base and train_refine) first the fgr, pha and bgr are augmented inside the Dataloader.

However, during the training, the background is augmented another time (with jitter, noise, affine) independent of the fgr and pha images. Isn't that redundant as the background already got augmented in the dataloader?

I appreciate any help that clarifies this point.

**Comment by PeterL1n** [comment]
It's not redundant.

The Dataloader augments the background image ones, at the training time, we composite the foreground onto the background using `src = pha * fgr + (1 - pha) * bgr`. Doing this directly will make the background in `src` and `bgr` completely the same, which is seldom the case in real life. So the augmentation in the training code is to make slight variation between the composited background and provided background.

**Comment by legnaib** [comment]
Thanks for your fast reply. Just to see if I've understood it correctly: First each single fgr and bgr image get augmented by the Dataloader. But during training we augment the combined fgr+bgr image again for more variation, right?

**Comment by PeterL1n** [comment]
In actual cases, a lot of the pre-captured background image will not perfectly align with the input image, because the camera could be shaken, the lighting can change over time etc. So we want to make sure that composited background has some variation than the pre-captured background given to the model. Otherwise, the model will simply overfit.
