### ISSUE TITLE
Direct prediction

### ISSUE THREAD

**Issue by kkuchynskyi** [PeterL1n/BackgroundMattingV2#19]
Hi!
I really like your paper, it's written so clearly. I think the whole community is thankful to you for the upcoming datasets. But I do not get one thing. Why do we need to use such a complicated approach if we can take just the difference between a background and a source? In this case, pixels which equal 0 will be our background.

**Comment by PeterL1n** [comment]
Simple pixel-level subtraction won't work, a easy intuition is that some part of the subject may have a similar color to the background unless you force the background to be a very different color, then it essentially becomes a green screen method. Additionally, almost all the time the background in the video slightly changes compared to the pre-captured background, maybe because the lighting changes over time due to the environment or there are shadows cast to the background by the subject. The neural network can semantically understand which part of the image is the subject and does not operate at pixel-level but with a more in-depth understanding.

In a more mathematical way, you will see that extracting foreground and alpha is an ill-posed problem and cannot be solved with algebra. An image `I` is a composition of a foreground subject `F` and a background `B` by an alpha coefficient matte `α` with the following equation:
```
I = αF + (1 - α)B
```
Given that we know `I` and `B`, mathematically you can't solve for `α` and `F`. A neural network's magic is to learn from the statistics of the massive training data and infer what `α` and `F` most likely to be for different parts of the image under different conditions.

Some method assumes `F = I`, then it will make the alpha matte computable where `α = 1` and  `α = 0`. However, it is wrong for the regions where alpha is partially transparent. Also, it assumes that for every video frame, `B` is absolutely the same as the pre-captured background, which is not true for the reason discussed above.
