### ISSUE TITLE
 foreground residual

### ISSUE THREAD

**Issue by Unitshockresponse** [PeterL1n/BackgroundMattingV2#7]
First  thank you for the great work you shared, I have a question. What is the foreground residual and what is it for?

**Comment by andreyryabtsev** [comment]
Hi @Unitshockresponse ,
"Foreground residual" refers to an output of our model that is then added to the source image (I) to produce the predicted foreground (F) ([here](https://github.com/PeterL1n/BackgroundMattingV2/blob/master/model/model.py#L95)). This predicted estimate of the foreground helps eliminate background color spill onto partial-opacity hairs and edges, which can otherwise occur if just compositing with an alpha matte and the source image. As described further in the paper, predicting the residual like that and adding it to the image simply happened to be a more efficient way of learning good foreground outputs.

**Comment by Unitshockresponse** [comment]
I get it,thank you
