### ISSUE TITLE
about model-backbone-scale

### ISSUE THREAD

**Issue by nostayup** [PeterL1n/BackgroundMattingV2#77]
thanks for your great work! it is amazing!
I have some questions about model-backbone-scale, hope to get your help:
①Why downsample the input image? Isn't it loss of information?
②Why the model does not work well when this parameter is set to 1
thank you very much！

**Comment by PeterL1n** [comment]
We need to downsample the resolution because it would otherwise be impractical to pass in full-resolution HD or 4K images directly through a standard convolutional network. Downsampling significantly reduces the computation. The second assumption is that the neural network doesn't really need high-resolution to identify the main location of the subject, low-resolution suffices. To recover the silhouette details that were missing at the low-resolution, we proposed the refiner module, which takes in the original resolution images and only refines the edges.

**Comment by nostayup** [comment]
> We need to downsample the resolution because it would otherwise be impractical to pass in full-resolution HD or 4K images directly through a standard convolutional network. Downsampling significantly reduces the computation. The second assumption is that the neural network doesn't really need high-resolution to identify the main location of the subject, low-resolution suffices. To recover the silhouette details that were missing at the low-resolution, we proposed the refiner module, which takes in the original resolution images and only refines the edges.

Thank you very much for your answer, but I still have some other doubts. I tested 4k without downsampling on the 3090 graphics card. The parameter is set to 1, and the speed did not drop significantly ，  so the  downsampling is considering lower performance  hardware?

If I don't have high requirements for speed, can I set the parameter to 1? Do different resolutions correspond to different parameters? Do you have relevant research or suggestions?

**Comment by PeterL1n** [comment]
You probably don't want to set it to 1. The model is not trained on setting it to 1. It is likely you won't get quality results.
