### ISSUE TITLE
 Test image size

### ISSUE THREAD

**Issue by Unitshockresponse** [PeterL1n/BackgroundMattingV2#91]
Hi,i have a question about inference_image.py.
Are you sending the original size image directly to the network?
any size is ok?

**Comment by PeterL1n** [comment]
Provide the network the original image. the height and width need to be divisible by 4.

You can configure the backbone_scale parameter, which controls how much the model downsamples the image internally before passing through the expansive backbone. But you do need to provide the network full resolution images, so that the refinement module will work on restoring high resolution detail.
