### ISSUE TITLE
Were you able to convert the pre-trained model to CoreML?

### ISSUE THREAD

**Issue by charankilari** [PeterL1n/BackgroundMattingV2#94]

**Comment by PeterL1n** [comment]
Conversion is possible. I have tried so and have succeeded. You do need to dig deep into the coremltools and implement some custom ops. But since last December I checked, even though the conversion is correct and the inference is correct, the speed is pretty slow in CoreML. The CropAndResize operation in CoreML is not very well optimized and it is very slow. Our model needs this operation to crop thousands of patches for refinement. I don't whether Apple has made improvement till now.

I don't have the conversion code no more. You will need to experiment yourself.

**Comment by charankilari** [comment]
Thanks. Good to know. You converted direct from Pytorch to CoreML using coremltools4.0 or you went via the onnx route?

**Comment by PeterL1n** [comment]
coremltools.
