### ISSUE TITLE
green line around person

### ISSUE THREAD

**Issue by ganjbakhshali** [PeterL1n/BackgroundMattingV2#99]
Hello
After processing is done, I separate Mask into Frames and use them for adding a new background.
But after merging by new background, a new green line around the person appears.
Any Ideas?
x-special/nautilus-clipboard

![Screenshot from 2021-05-19 13-34-40](https://user-images.githubusercontent.com/38520648/118786592-3600bf80-b8a7-11eb-9fbe-f7eb5e79908a.png)

**Comment by PeterL1n** [comment]
If you are compositing to a new background, the model already predict a clean alpha and foreground, you don't want to use the green screen output to do color keying again which is dumb. The green screen output is just for visualization. If your application does not give you that flexibility and only support color keying, then you can go with the green screen route, but your problem is their color keying algorithm, not our problem.

**Comment by luoww1992** [comment]
@ganjbakhshali,
i use the hsv to do it , result with green line
i am try to solve  it by  overflow color. but i can't find a good style, 
How do you solve the green line ？
some advice ?

**Comment by luoww1992** [comment]
@ganjbakhshali 
How do you solve the green line ？
